# Branch Protection Rules
# This file defines protection rules for main and develop branches

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions:
        users: []
        teams: []
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_conversation_resolution: true
      require_linear_history: false
      require_signatures: false
      lock_branch: false
      allow_fork_syncing: true

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions:
        users: []
        teams: []
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_conversation_resolution: true
      require_linear_history: false
      require_signatures: false
      lock_branch: false
      allow_fork_syncing: true
