backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'content: create {{collection}} "{{slug}}"'
    update: 'content: update {{collection}} "{{slug}}"'
    delete: 'content: delete {{collection}} "{{slug}}"'
    uploadMedia: 'media: add {{path}}'
    deleteMedia: 'media: delete {{path}}'

local_backend: true

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "apps/landing/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Category", name: "category", widget: "select", options: ["Technology", "Design", "Business", "Personal"], required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "docs"
    label: "Documentation"
    folder: "apps/landing/pages/docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "docs" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "select", options: ["Getting Started", "Components", "API", "Examples"], required: false }
      - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "apps/landing/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "authors"
    label: "Authors"
    folder: "apps/landing/content/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Email", name: "email", widget: "string", required: false }
      - { label: "Website", name: "website", widget: "string", required: false }
      - { label: "Social", name: "social", widget: "object", fields: [
          { label: "Twitter", name: "twitter", widget: "string", required: false },
          { label: "GitHub", name: "github", widget: "string", required: false },
          { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
        ]}

  - name: "categories"
    label: "Categories"
    folder: "apps/landing/content/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Color", name: "color", widget: "string", default: "#3B82F6" }
      - { label: "Icon", name: "icon", widget: "string", required: false }

  - name: "settings"
    label: "Site Settings"
    files:
      - file: "apps/landing/content/settings/site.yml"
        label: "Site Configuration"
        name: "site"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Site URL", name: "url", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Favicon", name: "favicon", widget: "image", required: false }
          - { label: "Social Media", name: "social", widget: "object", fields: [
              { label: "Twitter", name: "twitter", widget: "string", required: false },
              { label: "GitHub", name: "github", widget: "string", required: false },
              { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
            ]}

display_url: http://localhost:3000
